version: 2.1

executors:
  kotlin-executor:
    docker:
      - image: underabloodysky/my-image-circleci-ciriaqui

jobs:
  build:
    executor: kotlin-executor
    steps:
      - checkout

      - run:
          name: Setup environment
          command: |
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install -y lib32stdc++6

      - run:
          name: Change permissions of gradlew
          command: chmod +x ./gradlew

      - run:
          name: Build and Test
          command: ./gradlew clean build
          # Add more testing commands as needed

      - run:
          name: Generate JaCoCo Report
          command: ./gradlew jacocoTestReport --info

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonar --info

      - run:
          name: Un paso nuevo
          command: ./gradlew build jacocoTestReport sonar --info

      - store_artifacts:
          path: app/build/reports/tests
          destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: SonarCloud
