version: 2.1

executors:
  kotlin-executor:
    docker:
      - image: cimg/openjdk:17.0 # Use an appropriate JDK version

jobs:
  build:
    executor: kotlin-executor
    steps:
      - checkout # Checkout the code from your repository

      - run:
          name: Setup environment
          command: |
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install -y lib32stdc++6

      - run:
          name: Change permissions of gradlew
          command: chmod +x ./gradlew

      - run:
          name: Debug
          command: |
            ls -la src/test/resources/
            cat src/test/resources/application-test.properties
            
            chmod 644 src/test/resources/application-test.properties
            
            echo "Before sourcing:"
            env
            source src/test/resources/application-test.properties
            echo "After sourcing:"
            env

      - run:
          name: Build and Test
          command: ./gradlew clean build
          # Add more testing commands as needed

      - run:
          name: Generate JaCoCo Report
          command: ./gradlew jacocoTestReport --info

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonar --info

      - run:
          name: Un paso nuevo
          command: ./gradlew build jacocoTestReport sonar --info

      - store_artifacts:
          path: app/build/reports/tests # Adjust the path to your test reports
          destination: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: SonarCloud
